site_name: LeetCode Solutions and Algorithms
site_description: Comprehensive collection of LeetCode solutions with detailed explanations
site_author: Your Name
repo_url: https://github.com/yourusername/your-repo
repo_name: yourusername/your-repo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Overview: index.md
  - Solutions:
      - Array Problems:
          - Best Time to Buy and Sell Stock II: array_problems/best_time_to_buy_and_sell_stock_ll/README.md
          - Contains Duplicate: array_problems/contains_duplicate/README.md
          - Height Checker: array_problems/height_checker/README.md
          - Intersection of Arrays II: array_problems/intersection_of_two_arrays_ll/README.md
          - Max Consecutive Ones: array_problems/max_consecutive_ones/README.md
          - Move Zeroes: array_problems/move_zeroes/README.md
          - Plus One: array_problems/plus_one/README.md
          - Remove Duplicates from Sorted Array: array_problems/remove_duplicates_from_sorted_array/README.md
          - Remove Element: array_problems/remove_element/README.md
          - Replace Elements with Greatest Element on Right Side: array_problems/replace_elements_with_greatest_element_on_right_side/README.md
          - Rotate Array: array_problems/rotate_array/README.md
          - Single Number: array_problems/single_number/README.md
          - Sort Array By Parity: array_problems/sort_array_by_parity/README.md
          - Squares of Sorted Array: array_problems/squares_of_a_sorted_array/README.md
          - Two Sum: array_problems/two_sum/README.md

      - Math Problems:
          - Find Numbers with Even Digits: math_problems/find_numbers_with_even_number_of_digits/README.md
          - Fizz Buzz: math_problems/fizz_buzz/README.md
          - Power of three: math_problems/power_of_three/README.md
          - Roman to integer: math_problems/roman_to_integer/README.md

      - Sorting & Searching Problems:
          - Check if n and its double exist: sorting_searching_problems/check_if_n_and_its_double_exist/README.md
          - Duplicate Zeros: sorting_searching_problems/duplicate_zeros/README.md
          - Merge Sorted Array: sorting_searching_problems/merge_sorted_array/README.md
          - Valid mountain Array: sorting_searching_problems/valid_mountain_array/README.md

      - String Problems:
          - First Unique Character: string_problems/first_unique_character_in_a_string/README.md
          - Reverse Integer: string_problems/reverse_integer/README.md
          - Reverse String: string_problems/reverse_string/README.md
          - Valid anagram: string_problems/valid_anagram/README.md
          - Valid palindrome: string_problems/valid_palindrome/README.md

      - Data Structures & Algorithms:
          - Algorithms:
              - Searching:
                  - Binary Search: frontendmasters/algorithms/searching/binary_search/README.md
                  - Linear Search: frontendmasters/algorithms/searching/linear_search/README.md
                  - Two crystal balls: frontendmasters/algorithms/searching/two_crystal_balls/README.md
              - Sorting:
                  - Bubble Sort: frontendmasters/algorithms/sorting/bubble_sort/README.md
                  - Heap Sort: frontendmasters/algorithms/sorting/heap_sort/README.md
                  - Insertion Sort: frontendmasters/algorithms/sorting/insertion_sort/README.md
                  - Merge Sort: frontendmasters/algorithms/sorting/merge_sort/README.md
                  - Quick Sort: frontendmasters/algorithms/sorting/quick_sort/README.md
                  - Radix sort: frontendmasters/algorithms/sorting/radix_sort/README.md
              - Tree traversal:
                  - Breadth first: frontendmasters/algorithms/tree_traversal/breadth_first/README.md
                  - Depth first: frontendmasters/algorithms/tree_traversal/depth_first/README.md
              - Recursion: frontendmasters/algorithms/recursion/README.md
              - Pathfinding:
                  - Dijkstra: frontendmasters/algorithms/pathfinding/dijkstra/README.md
          - Data Structures:
              - Probabilistic:
                  - Bloom Filter: frontendmasters/data_structures/probabilistic/bloom_filter/README.md
              - Linked lists:
                  - Singly linked: frontendmasters/data_structures/linked_lists/singly_linked/README.md
              - Arrays:
                  - Array List: frontendmasters/data_structures/arrays/array_list/README.md
              - Trees:
                  - Avl Tree: frontendmasters/data_structures/trees/avl_tree/README.md
                  - Binary search Tree: frontendmasters/data_structures/trees/binary_search_tree/README.md
                  - Trie: frontendmasters/data_structures/trees/trie/README.md
              - Graphs: frontendmasters/data_structures/graphs/README.md

plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourusername

docs_dir: src
