name: black-action
on:
  pull_request:
    types:
      - opened
      - synchronize # Consider running on updates to PR as well
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # Checkout the PR branch
          token: ${{ secrets.GITHUB_TOKEN }} # Ensure you have push access

      - name: Check files using the black formatter
        uses: datadog/action-py-black-formatter@v2.1
        id: action_black

      - name: Commit and Push if changes
        if: steps.action_black.outputs.is_modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply black formatting"
          git push
