name: Run Tests and Update Documentation

on:
  push:
    branches:
      - main
      - master

jobs:
  test-and-update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=src tests/ -v > test_results.txt
          python -m pytest --cov=src --cov-report=xml tests/

      - name: Generate coverage badge
        run: |
          COVERAGE=$(python -c "import xml.etree.ElementTree as ET; print(ET.parse('coverage.xml').getroot().attrib['line-rate'])")
          COVERAGE_PCT=$(python -c "print(round(float('${COVERAGE}') * 100, 2))")
          echo "COVERAGE_PCT=${COVERAGE_PCT}" >> $GITHUB_ENV
          echo "[![Coverage](https://img.shields.io/badge/Coverage-${COVERAGE_PCT}%25-${COVERAGE_PCT_COLOR})]()" > coverage_badge.txt

          # Determine color based on coverage percentage
          if (( $(echo "${COVERAGE_PCT} >= 90" | bc -l) )); then
            echo "COVERAGE_PCT_COLOR=brightgreen" >> $GITHUB_ENV
          elif (( $(echo "${COVERAGE_PCT} >= 80" | bc -l) )); then
            echo "COVERAGE_PCT_COLOR=green" >> $GITHUB_ENV
          elif (( $(echo "${COVERAGE_PCT} >= 70" | bc -l) )); then
            echo "COVERAGE_PCT_COLOR=yellowgreen" >> $GITHUB_ENV
          elif (( $(echo "${COVERAGE_PCT} >= 60" | bc -l) )); then
            echo "COVERAGE_PCT_COLOR=yellow" >> $GITHUB_ENV
          else
            echo "COVERAGE_PCT_COLOR=red" >> $GITHUB_ENV
          fi

      - name: Update README.md with test results and coverage
        run: |
          # Create updated README content
          if grep -q "## Test Results" README.md; then
            # If section exists, replace it
            sed -i '/## Test Results/,/## /c\## Test Results\n\n```\n'"$(cat test_results.txt)"'\n```\n\n'"$(cat coverage_badge.txt)"'\n\n## ' README.md
          else
            # If section doesn't exist, append it
            echo -e "\n## Test Results\n\n\`\`\`\n$(cat test_results.txt)\n\`\`\`\n\n$(cat coverage_badge.txt)\n" >> README.md
          fi

      - name: Update src/index.md with test results and coverage
        run: |
          # Create updated index.md content
          if grep -q "## Test Results" src/index.md; then
            # If section exists, replace it
            sed -i '/## Test Results/,/## /c\## Test Results\n\n```\n'"$(cat test_results.txt)"'\n```\n\n'"$(cat coverage_badge.txt)"'\n\n## ' src/index.md
          else
            # If section doesn't exist, append it
            echo -e "\n## Test Results\n\n\`\`\`\n$(cat test_results.txt)\n\`\`\`\n\n$(cat coverage_badge.txt)\n" >> src/index.md
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git add README.md src/index.md
          git commit -m "Update test results and coverage [skip ci]" || echo "No changes to commit"
          git push
