name: Update Coverage on Readme
on:
  push:
jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to destination repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p test_data
        
      - name: Run pytest and generate report
        run: |
          python -m pytest --cov=frontendmasters.Complete_Intro_to_Computer_Science.BinarySearchTree.binarySearchTree --cov-report term --cov-report xml > test_data/pytest-coverage.txt

      - name: Pytest coverage comment
        if: ${{ github.ref == 'refs/heads/master' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./data/pytest-coverage_4.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: Create Pull Request
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update coverage on Readme"
          commit-message: ":zap: Update coverage on Readme"
          body: |
            Update coverage on Readme
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/pytest-coverage-comment