name: Update Coverage on Readme
on:
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # Make sure to use a token with push access
          fetch-depth: 0 # Necessary for a comprehensive history
          ref: ${{ github.head_ref }} # Checkout the PR branch
          token: ${{ secrets.GITHUB_TOKEN }} # Use a token with push access

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest and generate report
        run: |
          python -m pytest --cov=frontendmasters --cov=ArrayExercise --cov=MathExercise --cov=Sorting_and_Searching_Exercise --cov=StringExercise --cov-report term --cov-report xml > test_data/pytest-coverage.txt

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./test_data/pytest-coverage.txt

      - name: Update Readme with Coverage
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

          # Pull latest changes from the remote repository
          git pull origin HEAD

          # Check if there are any changes
          if git diff --quiet README.md; then
              echo "No changes to README.md. Skipping commit."
          else
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add README.md

              # Commit and push only if there were changes
              git commit -m "Update README with coverage report"
              git push
          fi
